### ISSUE TITLE
Do we have a have migration for our database's design? 

### ISSUE THREAD

**Issue by huf0813** [divisi-developer-poros/poros-web-backend#6]
Guys, I just want to give a suggestion about this project. I think one of us has to **prepare the migrations tables** that can be used in this project. If there is no person who create this migrations, I don't see any possibilities of finished on time. 😴   

You can see that gorm has a [documentations ](https://gorm.io/docs/migration.html)about database relations, these are few examples of them : 

- `if err := db.Debug().Model(&model.Event{}).AddForeignKey("user_id", "users(id)", "cascade", "cascade").Error; err != nil {
	log.Fatal(err)
}`
- `if err := db.Debug().Model(&model.Balance{}).AddForeignKey("user_id", "users(id)", "cascade", "cascade").Error; err != nil {
		log.Fatal(err)
	}`

Actually this is not that hard, just need a chill and drop of coffee to work on this. Wdyt?
@elingp @Endrawan @fikrimus35 @AFauzulh @marveltimothyy @gustianaditama

**Comment by Endrawan** [comment]
Didn't we already giving out the migration job included on the CRUD one? Well if you want to start working on the migrations then go on. But if you're busy, i think i can give it a shot. Wdyt @huf0813 ?

**Comment by huf0813** [comment]
Not busy at all 😸. I just realize that our job now is just focus on an table without any relationship to other table. Relationship will be next objective after finishing the individual table. Is this statement true? @Endrawan

**Comment by Endrawan** [comment]
Well that's basically correct. And i think this is my mistake because i didn't considerate about that when giving out the job. So how about we take care the relationship when this current goal are finished along with finding the bug?

**Comment by huf0813** [comment]
Blaming yourself isn't solution, there is no mistake. We just improving our milestone trough the discussions. Yes, we can work on the relationship after individual table is done. Well done @Endrawan 👍
